"""'Initial_Migration'

Revision ID: 210e45ad8ca8
Revises: a5ec7d8fa982
Create Date: 2023-03-02 18:01:34.158042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210e45ad8ca8'
down_revision = 'a5ec7d8fa982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
