"""'Added_Foreign_Key_Posts_Authot_id'

Revision ID: 44896e6d3d66
Revises: b13fa1efd235
Create Date: 2023-03-05 19:11:28.344183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44896e6d3d66'
down_revision = 'b13fa1efd235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['poster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
