"""'forget_slug_column'

Revision ID: 776d1ae9c338
Revises: 45f0b054de74
Create Date: 2023-03-03 23:27:25.199528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776d1ae9c338'
down_revision = '45f0b054de74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
